#!/bin/sh

fee_test()
{
    local expected=$1
    shift
    if [ "${expected#:}" = "$expected" ] && [ "${expected#?:}" = "$expected" ]
    then
        if [ "$(./feestamp "$*")" != "$expected" ]
        then
            echo "./feestamp $* doesn't give $expected" >&2
            exit 1
        fi
        if [ ${1%%-*} -ge 1984 ] && [ ${1%%-*} -lt 2048 ]
        then
            if [ "$(date +'%F %T' -d "$*")" != "$( ./feedate $expected)" ]
            then
                echo "./feedate $expected doesn't give $*" >&2
                exit 7
            fi
            if [ "$(date +'%F %T' -d "$*")" != "$( ./decode $expected)" ]
            then
                echo "./decode $expected doesn't give $*" >&2
                exit 17
            fi
        fi
        if false && [ ${1%%-*} -ge 1920 ] && [ ${1%%-*} -lt 1984 ]
        then
            decoded=$(HEXEPOCH=1920  ./feedate $expected)
            if [ "$(date +'%F %T' -d "$*")" != "$decoded" ]
            then
                echo "./feedate $expected doesn't give $*" >&2
                exit 7
            fi
            decoded=$(HEXEPOCH=1920  ./decode $expected)
            if [ "$(date +'%F %T' -d "$*")" != "$decoded" ]
            then
                echo "./decode $expected doesn't give $*" >&2
                exit 17
            fi
        fi
    else
        # Time part only
        local measured=$( ./feestamp "$*")
        if [ "${measured#*:}" != "${expected#*:}" ]
        then
            echo "./feestamp $* doesn't end with :${expected#*:}" >&2
            exit 1
        fi
        measured=$( ./feedate $expected | cut -d ' ' -f 2)
        if [ "$measured" != "$*" ]
        then
            echo "./feedate $expected doesn't give $*" >&2
            exit 9
        fi
        measured=$( ./decode $expected | cut -d ' ' -f 2)
        if [ "$measured" != "$*" ]
        then
            echo "./decode $expected doesn't give $*" >&2
            exit 19
        fi
    fi
}

fe_test()
{
    local expected=$1
    shift
    if [ "${expected#.}" = "$expected" ] && [ "${expected#?.}" = "$expected" ]
    then
        if [ "$(./festamp "$*")" != "$expected" ]
        then
            echo HEXEPOCH $HEXEPOCH
            echo "./festamp $* doesn't give $expected" >&2
            exit 1
        fi
        if [ "$(date +'%F %T' -d "$*")" != "$( ./fedate $expected)" ]
        then
            echo "./fedate $expected doesn't give $*" >&2
            exit 7
        fi
        if [ "$(date +'%F %T' -d "$*")" != "$( ./decode $expected)" ]
        then
            echo "./decode $expected doesn't give $*" >&2
            exit 17
        fi
    else
        # Time part only
        local measured=$( ./festamp "$*")
        if [ "${measured#*.}" != "${expected#*.}" ]
        then
            echo "./festamp $* doesn't end with :${expected.*:}" >&2
            exit 1
        fi
        measured=$( ./fedate $expected | cut -d ' ' -f 2)
        if [ "$measured" != "$*" ]
        then
            echo "./fedate $expected doesn't give $*" >&2
            exit 9
        fi
        measured=$( ./decode $expected | cut -d ' ' -f 2)
        if [ "$measured" != "$*" ]
        then
            echo "./decode $expected doesn't give $*" >&2
            exit 19
        fi
    fi
}

feedate_test()
{
    local original=$1
    local expected="$2 ${3-00:00:00}"
    if [ -z "$HEXEPOCH" ]
    then
        if [ "$(./feedate $original)" != "$expected" ]
        then
            echo "./feedate $original doesn't give $expected"
            exit 21
        fi
        if [ "$(./decode $original)" != "$expected" ]
        then
            echo "./decode $original doesn't give $expected"
            exit 22
        fi
    else
        if [ "$(HEXEPOCH=$HEXEPOCH ./feedate $original)" != "$expected" ]
        then
            echo "HEXEPOCH=$HEXEPOCH ./feedate $original doesn't give $expected"
            exit 23
        fi
        if [ "$(HEXEPOCH=$HEXEPOCH ./decode $original)" != "$expected" ]
        then
            echo "HEXEPOCH=$HEXEPOCH ./decode $original doesn't give $expected"
            exit 24
        fi
    fi
}

fedate_test()
{
    local original=$1
    local expected="$2 ${3-00:00:00}"
    if [ -z "$HEXEPOCH" ]
    then
        if [ "$(./fedate $original)" != "$expected" ]
        then
            echo "./fedate $original doesn't give $expected"
            exit 31
        fi
        if [ "$(./decode $original)" != "$expected" ]
        then
            echo "./decode $original doesn't give $expected"
            exit 32
        fi
    else
        if [ "$(HEXEPOCH=$HEXEPOCH ./fedate $original)" != "$expected" ]
        then
            echo "HEXEPOCH=$HEXEPOCH ./fedate $original doesn't give $expected"
            exit 33
        fi
        if [ "$(HEXEPOCH=$HEXEPOCH ./decode $original)" != "$expected" ]
        then
            echo "HEXEPOCH=$HEXEPOCH ./decode $original doesn't give $expected"
            exit 33
        fi
    fi
}

# Pretend the internal clock is in atomic time
# so that leap seconds are expressible
export TZ=right/UTC

fee_test 0008:0000 1920-01-01
fee_test d3ec:8000 1972-12-30 08:00:00
fee_test d3f1:b800 1972-12-31 23:30:00
fee_test d3f1:bfef 1972-12-31 23:59:60
fee_test d402:0000 1973-01-01 00:00:00
fee_test 0000:0000 1984-01-01
fee_test 0303:0303 1984-10-01 12:11:18
fee_test 0303:3030 1984-10-01 15:00:45
fee_test 03ec:0000 1984-12-29
fee_test 03f0:0000 1984-12-30
fee_test 03f2:0000 1984-12-31
fee_test 0404:0000 1985-01-01
fee_test 2810:0000 1994-01-02
fee_test 400c:0000 2000-01-01
fee_test 43ec:0000 2000-12-30
fee_test 43f0:0000 2000-12-31
fee_test 4402:0000 2001-01-01
fee_test 7777:7777 2013-11-13 19:28:07
fee_test 8167:094b 2016-05-04 12:34:56
fee_test 816a:0000 2016-05-06 00:00:00
fee_test 816b:0c0d 2016-05-06 12:45:13
fee_test 816b:bfee 2016-05-06 23:59:59
fee_test 83fd:bfef 2016-12-31 23:59:60
fee_test 8765:4321 2017-11-07 16:11:46
fee_test 8888:8888 2018-02-22 08:32:08
fee_test b00c:0000 2028-01-01
fee_test b3ec:0000 2028-12-30
fee_test b3f0:0000 2028-12-31
fee_test b402:0000 2029-01-01
(
    export TZ=right/Asia/Kolkata
    fee_test d402:57ee 1973-01-01 05:29:59
    fee_test d402:57ef 1973-01-01 05:29:60
    fee_test d402:5800 1973-01-01 05:30:00
) || exit 7

fee_test :0000 00:00:00
fee_test 1:0000 12:00:00
fee_test :0001 00:00:01
fee_test :000e 00:00:14
fee_test :0010 00:00:15
fee_test :0011 00:00:16
fee_test :0040 00:01:00
fee_test :0080 00:02:00
fee_test :00c0 00:03:00
fee_test :0400 00:15:00
fee_test :0800 00:30:00
fee_test :0c00 00:45:00
fee_test :1000 01:00:00
fee_test 1:1000 13:00:00
fee_test :b000 11:00:00
fee_test 1:b000 23:00:00

fee_test :0110 00:04:00
fee_test :0150 00:05:00
fee_test :03ee 00:14:59
fee_test :0550 00:20:00
fee_test :0aa0 00:40:00
fee_test :0fee 00:59:59

fe_test e000.8000 1920-01-01
fe_test ed3e.c800 1972-12-30 08:00:00
fe_test ed3f.1b80 1972-12-31 23:30:00
fe_test ed40.2000 1973-01-01 00:00:00
fe_test f000.0000 1984-01-01
fe_test f030.3303 1984-10-01 15:00:45
fe_test f03e.c000 1984-12-29
fe_test f03f.0000 1984-12-30
fe_test f03f.2000 1984-12-31
fe_test f040.4000 1985-01-01
fe_test f281.0000 1994-01-02
fe_test f400.c000 2000-01-01
fe_test f43e.c000 2000-12-30
fe_test f43f.0000 2000-12-31
fe_test f440.2000 2001-01-01
fe_test f816.a000 2016-05-06 00:00:00
fe_test fb00.c000 2028-01-01
fe_test fb3e.c000 2028-12-30
fe_test fb3f.0000 2028-12-31
fe_test fb40.2000 2029-01-01
(
    export TZ=right/Asia/Kolkata
    fe_test ed40.257e 1973-01-01 05:29:45
    fe_test ed40.2580 1973-01-01 05:30:00
) || exit 7

fe_test .0000 00:00:00
fe_test .1000 12:00:00
fe_test .0001 00:00:15
fe_test .0004 00:01:00
fe_test .0008 00:02:00
fe_test .000c 00:03:00
fe_test .0040 00:15:00
fe_test .0080 00:30:00
fe_test .00c0 00:45:00
fe_test .0100 01:00:00
fe_test .1100 13:00:00
fe_test .0b00 11:00:00
fe_test .1b00 23:00:00

fe_test .0011 00:04:00
fe_test .0015 00:05:00
fe_test .0055 00:20:00
fe_test .00aa 00:40:00

HEXEPOCH=1920 feedate_test    8:    1920-01-01
HEXEPOCH=1920 feedate_test d3ec:8   1972-12-30 08:00:00
HEXEPOCH=1920 feedate_test d3f1:b8  1972-12-31 23:30:00
HEXEPOCH=1920 feedate_test d402:    1973-01-01 00:00:00
unset HEXEPOCH=
feedate_test e0008:    1920-01-01
feedate_test ed3ec:8   1972-12-30 08:00:00
feedate_test ed3f1:b8  1972-12-31 23:30:00
feedate_test ed402:    1973-01-01 00:00:00
feedate_test     :     1984-01-01
feedate_test  303:0303 1984-10-01 12:11:18
feedate_test  303:303  1984-10-01 15:00:45
feedate_test  3ec:     1984-12-29
feedate_test  3f0:     1984-12-30
feedate_test  3f2:     1984-12-31
feedate_test  404:     1985-01-01
feedate_test 2810:     1994-01-02
feedate_test 400c:     2000-01-01
feedate_test 43ec:     2000-12-30
feedate_test 43f0:     2000-12-31
feedate_test 4402:     2001-01-01
feedate_test 816a:     2016-05-06
feedate_test b00c:     2028-01-01
feedate_test b3ec:     2028-12-30
feedate_test b3f0:     2028-12-31
feedate_test b402:     2029-01-01

HEXEPOCH=1920 fedate_test    .8    1920-01-01
HEXEPOCH=1920 fedate_test d3e.c8   1972-12-30 08:00:00
HEXEPOCH=1920 fedate_test d3f.1b8  1972-12-31 23:30:00
HEXEPOCH=1920 fedate_test d40.2     1973-01-01 00:00:00
unset HEXEPOCH=
fedate_test e000.8   1920-01-01
fedate_test ed3e.c8  1972-12-30 08:00:00
fedate_test ed3f.1b8 1972-12-31 23:30:00
fedate_test ed40.2   1973-01-01 00:00:00
fedate_test     .    1984-01-01
fedate_test  30.30303 1984-10-01 12:11:18
fedate_test  30.3303 1984-10-01 15:00:45
fedate_test  3e.c    1984-12-29
fedate_test  3f.0    1984-12-30
fedate_test  3f.2    1984-12-31
fedate_test  40.4    1985-01-01
fedate_test 281.0    1994-01-02
fedate_test 400.c    2000-01-01
fedate_test 43e.c    2000-12-30
fedate_test 43f.0    2000-12-31
fedate_test 440.2    2001-01-01
fedate_test 816.a    2016-05-06
fedate_test b00.c    2028-01-01
fedate_test b3e.c    2028-12-30
fedate_test b3f.0    2028-12-31
fedate_test b40.2    2029-01-01

[ -n "$( ./feestamp)" ] ||
{
    echo "Current time failed" >&2
    exit 2
}

if [ "$(./feedate 8bdd:6fef)" != "2018-12-22 18:59:60" ]
then
    echo "Standalone feedate test failed" >&2
    exit 8
fi

[ -n "$( ./festamp)" ] ||
{
    echo "Current fe time failed" >&2
    exit 2
}

if [ "$(./fedate 8bd.d6fef)" != "2018-12-22 18:59:60" ]
then
    echo "Standalone fedate test failed" >&2
    exit 8
fi
